# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef899ce4dbcc78d8a03c32457e245e43c8c611abd3d49f98f1d3fd5ddbc7d59fa58b5cdc10d896415e4e6392407dd3d7a7b9d07ff28d5b9257477458394921d6

test:
  secret_key_base: e7a3d544f800ddbe93b5d56498009a9f9b830e7d36ba14e436c0cf6372d21a663e79b6e65e674750833f811674e2236eadeb20eebd71c07d6e4d5b301d4ed95b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
